hslavich_onelogin_saml:
  # Basic settings
  idp:
    entityId: 'https://samltest.id/saml/idp'
    singleSignOnService:
      url: 'https://samltest.id/idp/profile/SAML2/POST/SSO'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: '%env(SAML_IDP_CERT)%'
  sp:
    entityId: 'http://localhost:8000/saml/metadata'
    assertionConsumerService:
      url: 'http://localhost:8000/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      url: 'http://localhost:8000/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: '%env(JWT_SECRET_KEY)%'
  # Optional settings
  baseurl: 'http://localhost:8000/saml/'
  strict: true
  debug: true
  security:
    nameIdEncrypted: false
    authnRequestsSigned: false
    logoutRequestSigned: false
    logoutResponseSigned: false
    wantMessagesSigned: false
    wantAssertionsSigned: false
    wantNameIdEncrypted: false
    requestedAuthnContext: true
    signMetadata: false
    wantXMLValidation: true
    relaxDestinationValidation: false
    destinationStrictlyMatches: true
    rejectUnsolicitedResponsesWithInResponseTo: false
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Tech User'
      emailAddress: 'techuser@example.com'
    support:
      givenName: 'Support User'
      emailAddress: 'supportuser@example.com'
    administrative:
      givenName: 'Administrative User'
      emailAddress: 'administrativeuser@example.com'
  organization:
    en:
      name: 'Example'
      displayname: 'Example'
      url: 'http://example.com'
